# Working with NUMPY 
at first we need to import the NUMPY module

In [5]:

import numpy as np

In [4]:
arr_ran = np.arange(0,10,1)
arr_ran

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(arr_ran)

numpy.ndarray

# Creating 2-dimensional array
2-D array can be created using functions like 
zeros(),full(),

In [7]:

list_1 = [1, 2, 3, 4] 
list_2 = [5, 6, 7, 8] 
list_3 = [9, 10, 11, 12] 
print(np.array([list_1, list_2, list_3])) 
print(np.empty([4, 3], dtype=int))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
#Create array using functions 
print(np.arange(1, 10))

print(np.linspace(1, 10, 3)) 

print(np.zeros(5, dtype=int)) 

print(np.ones(9, dtype=float)) 

print(np.random.rand(5)) 

print(np.random.randint(5, size=10)) 


[1 2 3 4 5 6 7 8 9]
[ 1.   5.5 10. ]
[0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.4021572  0.96346805 0.08762521 0.2298429  0.03991627]
[4 4 4 3 3 1 3 2 3 3]


In [11]:
#2d array creations 
print(np.zeros([4, 3], dtype = np.int32)) 

print(np.ones([4, 3], dtype = np.int32)) 

print(np.full([2, 2], 67, dtype = int)) 

print(np.eye(4))


[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[67 67]
 [67 67]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
arr = np.asarray([1, 2, 3, 4]) 
# check size of the array 
print("Size:", arr.size) 

# check len of the array 
print("len:", len(arr)) 

# check shape of the array 
print("Shape:", arr.shape) 

# check dtype of the array elements 
print("Datatype:", arr.dtype) 

# change the dtype to 'float64' 
arr = arr.astype('float64') 
print(arr) 
print("Datatype:", arr.dtype) 

# convert array to list 
lis = arr.tolist() 
print("\nList:", lis) 
print(type(lis))


Size: 4
len: 4
Shape: (4,)
Datatype: int64
[1. 2. 3. 4.]
Datatype: float64

List: [1.0, 2.0, 3.0, 4.0]
<class 'list'>


In [13]:
# Two dimensional array 

list_1 = [1, 2, 3, 4] 
list_2 = [5, 6, 7, 8] 
list_3 = [9, 10, 11, 12] 
arr = np.array([list_1, list_2, list_3]) 

# check size of the array 
print("Size:", arr.size) 

# check length of the array 
print("Length:", len(arr)) 

# check shape of the array 
print("Shape:", arr.shape) 

# check dtype of the array elements 
print("Datatype:", arr.dtype) 

# change the dtype to 'float64' 
arr = arr.astype('float64') 
print(arr) 
print(arr.dtype) 

# convert array to list 
lis = arr.tolist() 
print("\nList:", lis) 
print(type(lis))


Size: 12
Length: 3
Shape: (3, 4)
Datatype: int64
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
float64

List: [[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0], [9.0, 10.0, 11.0, 12.0]]
<class 'list'>


In [14]:
#saving and loading from file 

# the array is saved in the file data.npy 
np.save("data", np.arange(5)) 

# the array is loaded into b 
print(np.load("data.npy"))

[0 1 2 3 4]


In [16]:
# sorting a one dimensional 
a = np.array([12, 15, 10, 1]) 
print("Array before sorting",a) 
a.sort() 
print("Array after sorting",a)


Array before sorting [12 15 10  1]
Array after sorting [ 1 10 12 15]


In [17]:
# Adding the values at the end 
# of a numpy array 
print("Original Array:", arr) 

# appending to the array 
arr = np.append(arr, [7]) 
print("Array after appending:", arr)


Original Array: [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Array after appending: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.  7.]


In [19]:
#inserting element to array
arr = np.asarray([1, 2, 3, 4]) 

print("1D arr:", arr) 
print("Shape:", arr.shape) 

# Inserting value 9 at index 1 
a = np.insert(arr, 1, 9) 
print("\nArray after insertion:", a) 
print("Shape:", a.shape)


1D arr: [1 2 3 4]
Shape: (4,)

Array after insertion: [1 9 2 3 4]
Shape: (5,)


In [20]:
#removing elements
print("Original arr:", arr) 
print("Shape : ", arr.shape) 

# deletion from 1D array 
object = 2
a = np.delete(arr, object) 
print("\ndeleteing the value at index {} from array:\n {}".format(object,a)) 
print("Shape : ", a.shape)


Original arr: [1 2 3 4]
Shape :  (4,)

deleteing the value at index 2 from array:
 [1 2 4]
Shape :  (3,)


In [21]:

# Reshaping Arrays
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]) 

print("Array: " + str(array)) 

# converting it to 2-D from 1-D array 
reshaped1 = array.reshape((4, array.size//4)) 

print("First Reshaped Array:") 
print(reshaped1) 

reshaped2 = np.reshape(array, (2, 8)) 

print("\nSecond Reshaped Array:") 
print(reshaped2)


Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Second Reshaped Array:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [22]:
#combining arrays
arr1 = np.array([[2, 4], [6, 8]]) 
arr2 = np.array([[3, 5], [7, 9]]) 

# combining on axis 0 
gfg = np.concatenate((arr1, arr2), axis = 0) 
print(gfg) 

# combining on axis 1 
gfg = np.concatenate((arr1, arr2), axis = 1) 
print("\n", gfg) 

# combining on axis None 
gfg = np.concatenate((arr1, arr2), axis = None) 
print("\n", gfg) 

# stacking two arrays on one another 
print(np.stack((arr1, arr2), axis=1))


[[2 4]
 [6 8]
 [3 5]
 [7 9]]

 [[2 4 3 5]
 [6 8 7 9]]

 [2 4 6 8 3 5 7 9]
[[[2 4]
  [3 5]]

 [[6 8]
  [7 9]]]


In [23]:
#spliting arrays 
# Making of a 3x3 array 
a = np.arange(9).reshape(3, 3) 
print(a) 

# Horizontal splitting of array 'a' 
# using 'split' with axis parameter = 1. 
print("Splitted array in horizontal form:\n", np.split(a, 3, 1)) 

# Vertical splitting of array 'a' 
# using 'split' with axis parameter = 0. 
print("\nSplitted array in vertical form:\n", np.split(a, 3, 0))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
Splitted array in horizontal form:
 [array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]

Splitted array in vertical form:
 [array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [24]:
# Horizontal splitting of array 
# 'a' using np.hsplit(). 
print(a) 
print("Splitted array in horizontally to form:", np.hsplit(a, 3))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
Splitted array in horizontally to form: [array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [25]:
# Vertical splitting of array 'a' 
# using np.vsplit(). 
print("Splitted array in vertically to form:", np.vsplit(a, 3))


Splitted array in vertically to form: [array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [26]:
#slicing of array
print(arr) 

# a[start:stop:step] 
print("a[-2:7:1] = ",arr[-2:7:1]) 

print("a[1:] = ",arr[1:])


[1 2 3 4]
a[-2:7:1] =  [3 4]
a[1:] =  [2 3 4]


In [27]:
# Integer Indexing 
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]]) 
print(a[[0 ,1 ,2 ],[0 ,0 ,1]]) 

# Boolean Indexing 
a = np.array([10, 40, 80, 50, 100]) 
print(a[a>50])


[1 3 6]
[ 80 100]


In [28]:
# Copying Numpy array with normal assignment 
nc = arr 

# both arr and nc have same id 
print("Normal Assignment copy") 
print("id of arr:", id(arr)) 
print("id of nc:", id(nc)) 

# updating nc 
nc[0]= 12

# printing the values 
print("original array:", arr) 
print("assigned array:", nc)


Normal Assignment copy
id of arr: 4405404528
id of nc: 4405404528
original array: [12  2  3  4]
assigned array: [12  2  3  4]


In [ ]:
# Creating a deep copy of NumPy 
# array creating copy of array 
c = arr.copy() 
	
# both arr and c have different id 
print("id of arr:", id(arr)) 
print("id of c:", id(c)) 
	
# changing original array 
# this will not effect copy 
arr[0] = 12
	
# printing array and copy 
print("original array:", arr) 
print("copy:", c)

In [29]:
# Defining both the matrices 
a = np.array([5, 72, 13, 100]) 
b = np.array([2, 5, 10, 30]) 

# Performing addition using numpy function 
print("Addition:", np.add(a, b)) 

# Performing subtraction using numpy function 
print("Subtraction:", np.subtract(a, b)) 

# Performing multiplication using numpy function 
print("Multiplication:", np.multiply(a, b)) 

# Performing division using numpy functions 
print("Division:", np.divide(a, b)) 

# Performing mod on two matrices 
print("Mod:", np.mod(a, b)) 

#Performing remainder on two matrices 
print("Remainder:", np.remainder(a,b)) 

# Performing power of two matrices 
print("Power:", np.power(a, b)) 

# Performing Exponentiation 
print("Exponentiation:", np.exp(b))

Addition: [  7  77  23 130]
Subtraction: [ 3 67  3 70]
Multiplication: [  10  360  130 3000]
Division: [ 2.5        14.4         1.3         3.33333333]
Mod: [ 1  2  3 10]
Remainder: [ 1  2  3 10]
Power: [                 25          1934917632        137858491849
 1152921504606846976]
Exponentiation: [7.38905610e+00 1.48413159e+02 2.20264658e+04 1.06864746e+13]


In [30]:
an_array = np.array([[1, 2], [3, 4]]) 
another_array = np.array([[1, 2], [3, 4]]) 

comparison = an_array == another_array 
equal_arrays = comparison.all() 

print(equal_arrays)


True


In [32]:
arr = np.array([.5, 1.5, 2.5, 3.5, 4.5, 10.1]) 

# applying sqrt() method 
print("Square-root:", np.sqrt(arr)) 

# applying log() method 
print("Log Value: ", np.log(arr)) 

# applying absolute() method 
print("Absolute Value:", np.absolute(arr)) 

# applying sin() method 
print("Sine values:", np.sin(arr)) 

# applying ceil() method 
print("Ceil values:", np.ceil(arr)) 

# applying floor() method 
print("Floor Values:", np.floor(arr)) 

# applying round_() method 
print ("Rounded values:", np.round(arr))


Square-root: [0.70710678 1.22474487 1.58113883 1.87082869 2.12132034 3.17804972]
Log Value:  [-0.69314718  0.40546511  0.91629073  1.25276297  1.5040774   2.31253542]
Absolute Value: [ 0.5  1.5  2.5  3.5  4.5 10.1]
Sine values: [ 0.47942554  0.99749499  0.59847214 -0.35078323 -0.97753012 -0.62507065]
Ceil values: [ 1.  2.  3.  4.  5. 11.]
Floor Values: [ 0.  1.  2.  3.  4. 10.]
Rounded values: [ 0.  2.  2.  4.  4. 10.]


In [33]:
# 1D array 
arr = [20, 2, 7, 1, 34] 

# mean 
print("mean of arr:", np.mean(arr)) 

# median 
print("median of arr:", np.median(arr)) 

# sum 
print("Sum of arr(uint8):", np.sum(arr, dtype = np.uint8)) 
print("Sum of arr(float32):", np.sum(arr, dtype = np.float32)) 

# min and max 
print("maximum element:", np.max(arr)) 
print("minimum element:", np.min(arr)) 

# var 
print("var of arr:", np.var(arr)) 
print("var of arr(float32):", np.var(arr, dtype = np.float32)) 

# standard deviation 
print("std of arr:", np.std(arr)) 
print ("More precision with float32", np.std(arr, dtype = np.float32))


mean of arr: 12.8
median of arr: 7.0
Sum of arr(uint8): 64
Sum of arr(float32): 64.0
maximum element: 34
minimum element: 1
var of arr: 158.16
var of arr(float32): 158.16
std of arr: 12.576167937809991
More precision with float32 12.576168
